name: RunTestScripts
on:
  pull_request:
    branches:
      - tobereplacedwithrelevantbranch
    types: [opened, synchronize, reopened, ready_for_review]      
    paths:
      - 'src/mnggrp/*.fsx'      
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
#        os: [ubuntu-latest,windows-latest,macos-latest]        
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install .NET Core SDK 5.0.400
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.400'

      - name: Install Dotnet Tools
        run: dotnet tool restore

      - name: Paket restore
        run: dotnet paket restore

      - name: Paket generate fsx loaders
        run: dotnet paket generate-load-scripts --type fsx

      - name: Run Test
        run: dotnet fsi ./src/mnggrp/verifyHierAndGroups.fsx